AWSTemplateFormatVersion: '2010-09-09'
Description: WordPress EC2 Server with Automated Installation

Parameters:
    EnvironmentName:
        Type: String
        Default: wordpress

    KeyPairName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: EC2 Key Pair

    AmazonLinuxAMIID:
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

    WordPressInstance:
        Type: AWS::EC2::Instance

        Properties:
            InstanceType: t2.micro
            ImageId: !Ref AmazonLinuxAMIID
            KeyName: !Ref KeyPairName

            SubnetId:
                Fn::ImportValue: wordpress-PublicSubnet1

            SecurityGroupIds:
                - Fn::ImportValue: wordpress-WebServerSG

            Tags:
                - Key: Name
                  Value: wordpress-server

            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash

                    yum update -y

                    yum install -y httpd wget unzip

                    amazon-linux-extras enable php8.2

                    yum clean metadata

                    yum install -y php php-mysqlnd

                    systemctl start httpd
                    systemctl enable httpd

                    echo "Apache is working" > /var/www/html/health.html

                    cd /tmp

                    wget https://wordpress.org/latest.tar.gz

                    tar -xzf latest.tar.gz

                    cp -r wordpress/* /var/www/html/

                    chown -R apache:apache /var/www/html

                    chmod -R 755 /var/www/html

                    systemctl restart httpd

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WordPressInstance


  PublicIP:
    Description: Public IP Address
    Value: !GetAtt WordPressInstance.PublicIp


  PublicDNS:
    Description: Public DNS Name
    Value: !GetAtt WordPressInstance.PublicDnsName


  WordPressURL:
    Description: WordPress Website URL
    Value: !Sub 
      - "http://${PublicIP}"
      - PublicIP: !GetAtt WordPressInstance.PublicIp
       
